obj-m := kvm.o kvm-intel.o kvm-amd.o
kvm-objs := async_pf.o binary_stats.o coalesced_mmio.o compat-x86.o cpuid.o debugfs.o dirty_ring.o \
	 emulate.o eventfd.o guest_memfd.o hyperv.o i8254.o i8259.o ioapic.o irq_comm.o irq.o irqchip.o \
	 kvm_main.o kvm_onhyperv.o lapic.o \
	 mmu/mmu.o mmu/page_track.o mmu/spte.o mmu/tdp_iter.o mmu/tdp_mmu.o \
	 mtrr.o pmu.o pfncache.o smm.o x86.o xen.o
ifeq ($(CONFIG_KVM_VFIO),y)
kvm-objs += vfio.o
endif
kvm-intel-objs := ../hyperv.o vmx/hyperv.o vmx/hyperv_evmcs.o vmx/nested.o vmx/pmu_intel.o vmx/posted_intr.o \
	 vmx/vmx_onhyperv.o vmx/sgx.o vmx/vmcs12.o vmx/vmenter.o vmx/vmx.o
kvm-amd-objs := svm/avic.o svm/hyperv.o svm/nested.o svm/pmu.o svm/sev.o svm/svm_onhyperv.o svm/svm.o svm/vmenter.o

AFLAGS_svm/vmenter.o    := -iquote $(obj)
$(obj)/svm/vmenter.o: $(obj)/kvm-asm-offsets.h

AFLAGS_vmx/vmenter.o    := -iquote $(obj)
$(obj)/vmx/vmenter.o: $(obj)/kvm-asm-offsets.h

$(obj)/kvm-asm-offsets.h: $(obj)/kvm-asm-offsets.s FORCE
	$(call filechk,offsets,__KVM_ASM_OFFSETS_H__)

targets += kvm-asm-offsets.s
clean-files += kvm-asm-offsets.h


CFLAGS_kvm_main.o = -DKVM_MAIN
